import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { PortfolioData } from "./demoData";

const formatCurrency = (n: number) => "₹" + n.toLocaleString("en-IN");

export function generatePDFReport(data: PortfolioData) {
  const doc = new jsPDF();
  const { funds, metrics, scoreBreakdown, insights, redFlags, recommendations } = data;
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // primary blue
  doc.text("MF Portfolio X-Ray Report", 14, y);
  y += 10;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on ${new Date().toLocaleDateString("en-IN")}`, 14, y);
  y += 12;

  // Health Score
  doc.setFontSize(16);
  doc.setTextColor(30);
  doc.text(`Portfolio Health Score: ${metrics.healthScore}/100`, 14, y);
  y += 10;

  // Metrics
  doc.setFontSize(11);
  doc.setTextColor(60);
  const metricsText = [
    `XIRR: ${metrics.xirr}%`,
    `Total Value: ${formatCurrency(metrics.totalValue)}`,
    `Portfolio Overlap: ${metrics.portfolioOverlap}%`,
    `Annual Expense Drag: ${formatCurrency(metrics.annualExpenseDrag)}`,
  ];
  metricsText.forEach((m) => {
    doc.text(m, 14, y);
    y += 6;
  });
  y += 4;

  // Score Breakdown
  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text("Score Breakdown", 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(60);
  const breakdownEntries = [
    ["Performance (30%)", `${scoreBreakdown.performance}/100`],
    ["Diversification (25%)", `${scoreBreakdown.diversification}/100`],
    ["Cost Efficiency (25%)", `${scoreBreakdown.costEfficiency}/100`],
    ["Risk Alignment (20%)", `${scoreBreakdown.riskAlignment}/100`],
  ];
  breakdownEntries.forEach(([label, val]) => {
    doc.text(`${label}: ${val}`, 14, y);
    y += 6;
  });
  y += 4;

  // Funds Table
  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text("Your Funds", 14, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [["Fund Name", "Category", "Invested", "Current", "XIRR", "Status"]],
    body: funds.map((f) => [
      f.name,
      f.category,
      formatCurrency(f.amountInvested),
      formatCurrency(f.currentValue),
      `${f.xirr}%`,
      f.status,
    ]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [37, 99, 235] },
    margin: { left: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Recommendations
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text("Action Recommendations", 14, y);
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(60);
  recommendations.forEach((r, i) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(`${i + 1}. ${r.action}`, 14, y);
    y += 5;
    doc.setTextColor(100);
    doc.text(`   Impact: ${r.impact} (Score +${r.projectedScoreChange})`, 14, y);
    doc.setTextColor(60);
    y += 7;
  });

  // Red Flags
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text("Red Flags", 14, y);
  y += 8;
  doc.setFontSize(9);
  redFlags.forEach((f) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setTextColor(f.severity === "high" ? 220 : f.severity === "medium" ? 180 : 120, 60, 60);
    doc.text(`[${f.severity.toUpperCase()}] ${f.message}`, 14, y);
    y += 6;
  });

  // AI Insights
  if (y > 230) { doc.addPage(); y = 20; }
  y += 4;
  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text("AI Insights", 14, y);
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(60);
  insights.forEach((ins) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(`${ins.title}: ${ins.description}`, 14, y, { maxWidth: 180 });
    y += 10;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by MF Portfolio X-Ray • For informational purposes only", 14, 285);

  doc.save("Portfolio_XRay_Report.pdf");
}
